### ISSUE TITLE
Custom Component failing on HA 2024.9.0beta0

### ISSUE THREAD

**Issue by nickrout** [HASwitchPlate/openHASP-custom-component#148] opened 2024-08-29 03:45 UTC
## Version of the custom_component
0.7.4

## Configuration

Irrelevant as component does not load

```

## Describe the bug
Fails to load on restart after installing the beta

## Debug log

```text
2024-08-29 15:27:39.244 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration openhasp which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-08-29 15:27:44.710 ERROR (MainThread) [homeassistant.setup] Error during setup of component openhasp
  File "/config/custom_components/openhasp/__init__.py", line 215, in async_setup

```

**Comment by dgomes** [comment] 2024-08-29 09:34
you need to share the remaining lines...

**Comment by nickrout** [comment] 2024-08-29 19:50
sorry, silly me
```text

2024-08-29 15:27:40.719 WARNING (SyncWorker_10) [py.warnings] /usr/local/lib/python3.12/site-packages/urllib3
/connectionpool.py:1063: InsecureRequestWarning: Unverified HTTPS request is being made to host '192.168.20.2
'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advance
d-usage.html#ssl-warnings
--
2024-08-29 15:27:44.710 ERROR (MainThread) [homeassistant.setup] Error during setup of component openhasp
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/openhasp/__init__.py", line 215, in async_setup
    component.async_register_entity_service(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 266, in async_register_entity
_service
    service.async_register_entity_service(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1271, in async_register_entity_service
    raise HomeAssistantError("The schema is not an entity service schema")
homeassistant.exceptions.HomeAssistantError: The schema is not an entity service schema
```

**Comment by nickrout** [comment] 2024-08-29 20:24
It's not a debug log. I referred HA to 2024.8.3 because openhasp provides an important display for me, but I can upgrade again and get a debug log off needed. Let me know.

**Comment by drewancil** [comment] 2024-08-29 20:29
I can provide any needed logs from the beta

**Comment by dgomes** [comment] 2024-08-29 20:43
Well you are running Beta :) that is not supported... 

But I've pushed a commit that should fix it, you must use the ´main` branch

**Comment by nickrout** [comment] 2024-08-30 03:20
> Well you are running Beta :) that is not supported...
> 


I don't understand what you mean by this. Are you saying you will not support Home Assistant 2024.9? Because that is what the beta will become in 5 or 6 days.

**Comment by dgomes** [comment] 2024-08-30 10:00
I already pushed the fix...

The issue is the beta includes new features that have not yet been documented... I happen to be aware of them, but the documentation on this change has not been published yet! A common custom component developer would not know what is going on.

**Comment by nickrout** [comment] 2024-08-30 10:29
Fantastic, sorry that I misunderstood.

**Comment by dgomes** [comment] 2024-08-30 12:52
could use feedback if everything is OK :) @nickrout

**Comment by nickrout** [comment] 2024-08-30 20:20
Seems to work fine (on b1 now. ) many thanks.

**Comment by fvanroie** [comment] 2024-09-05 15:43
0.7.5 is released

**Closed by fvanroie** 2024-09-05 15:43 UTC
